const data = [
    { id: '1', title: 'EXIF DATA', 
    content: 'The global growth and high availability to which we are currently facing the use of professional cameras such as those available on smartphones we managed to capture great images, these photographs although first instance could go unnoticed we have important information called EXIF data or metadata is widely used by professional photographers to know the settings of a photograph offering information of the lens setting, the model, among other data that achieved the result of the photograph, but it is not all that includes also shares vulnerable information such as the location in which the photo was taken, by what device was taken, the time and date information that could be used for different purposes. \n\n'
            +'The EXIF (Exchangeable Image File Format) defines a set of TIFF (Tagged Image File Format) tags to describe photographic images. The specification uses existing file formats such as JPEG and TIFF. All JPEG files start with the binary value 0xFFD8 (SOI - Start Of Image) and end with 0xFFD9 (EOI - End Of Image). SOI and EOI are markers that have no subsequent data unlike the other markers that have a fixed structure and associated data. \n\n'
            +'According to Hartel and Thomson (2011), some authors consider it questionable to keep the term “photography” in the context of cyber media. These authors propose to distinguish exclusively between textual information and visual information, defining visual content as a container that encompasses the contributions of photography, illustration, infographics, video and 3D techniques. According to their perspective, categorizing the photographic image as just another visual content allows placing the analytical models developed by the social sciences at the core of the theoretical study of the visual message (Freixa, 2013). \n\n'
            +'As explained by some authors, the best explained EXIF data are metadata usually referred to as “data about data”, i.e. information of interest that complements the main content of a digital document. Digital images are stored in a variety of formats such as TIFF, JPEG, PSD or RAW among others. Each image format has different rules for how the different metadata formats are stored along with the file containing the image itself. Some of the different metadata containers for the different formats are: Exif/TIFF IFDs, Adobe XMP and IPTC-IIM. Each of these metadata containers has its own format that indicates the metadata properties that are stored, the order and their encoding in the container. In each container there is usually a subdivision with semantic criteria. These semantic groups are further divided into individual metadata properties. Each property has specific data types associated with it, such as character strings, numbers or vectors. Copyright strings can be stored by several containers with similar information, but possibly with subtly different semantics or structure (Sandoval Orozco et al., 2012). \n\n'
            +'The security of EXIF data is something that takes into consideration digital security and the manipulation or use of EXIF data for investigations has come to be dealt with by different internet sites such as social networks, for example in 2016 Facebook is obliged by court ruling to leave intact the metadata of the photos uploaded by users in order to check the authenticity of the images. As most smart cell phones and now also cameras are equipped with GPS functions, and some images include geo tags and IP addresses, this should be considered before when posting images with metadata on the web. If we do not want to show sensitive details of the photos it is recommended to remove the information from the images using the EXIF tools available in various tools such as Secure Surf. \n\n'
            +'\n Bibliography. \n\n'
            +'Freixa Pere. (2013). Analysis of photographic content: Some reflections on photography in digital media. Universitat Pompeu Fabra. \n\n'
            +'Ana S. David A. et al. (2012). Exif Tracking Anomalies in Forensic Mobile Image Metadata Analysis. Facultad de Informatica, Universidad Complutense de Madrid (UCM). \n\n'
            +'Digital Guide IONOS. (23 septiembre, 2020). EXIF: display and save image metadata. Retrieved May 6, 2024 from https://www.ionos.es/digitalguide/paginas-web/diseno-web/que-son-los-datos-exif/\n\n'
            +'Laura Cabello Gil. (2017). GEOLOCATION DATA AS AN INVESTIGATIVE MEASURE. ADVANCES IN THE CRIMINAL PROCEDURAL LEGAL SYSTEM. School of Law, Universidad Nacional De Educación a Distancia (UNED). Retrieved May 6, 2024 from https://dialnet.unirioja.es/servlet/dctes?codigo=109401\n\n'
            +'\n\n'
          },

    { id: '2', title: 'Cookies and Trackers', 
    content: 'Cookies often used on the Internet through browsers are text files that are used to identify the browser and their main reason is to give efficiency and improve the user experience by remembering passwords, events previously used within the page. Most cookies are used for the convenience of the user, but does not rule out the use that could be given by cybercriminals to track the browser. \n\n' 
            +'If they bring risks the use of cookies to navigation because we continue to occupy them, well their use is due to the management of login, how many of us is cumbersome to remember password and prefer that the browser remembers them. Personalization of ads, trackers that track and monitor analytical performance data, such as how many times you have visited a page or how much time you have spent on it. \n\n'
            +'\n Cookies \n\n'
            +'Within the cookies we have categories according to their activity time; The aforementioned session cookies that are stored in random access memory. Persistent cookies that are stored on the computer indefinitely, but with an expiration time. First-party cookies, created directly by the website you are using. They are usually safer because they are on sites such as https, but always check that they have not been breached by a recent data breach or cyberattack. Third-party cookies come from websites other than the ones users are visiting at the time, usually because they are linked to advertisements on that page. Third-party cookies allow advertising or analytics companies to track a persons browsing history across the web on any site that has their ads. Third-party persistent supercookies that are permanently installed on users computers. They have the unique ability to reappear after they have been “deleted” from the computer. \n\n'
            +'Cookies are part of the HTTP protocol, which is the protocol used to navigate web pages. Using requests and responses they are used to exchange messages between the server and the client. Cookies were implemented in response to repeated web page query requests as a solution to fast user response and configuration. \n\n'
            +'The structure of a cookie is named Set-Cookie and is composed of name=value, domain=domain_name, expires=cookie_expiration_date. \n\n'
            +'\n Types of cookies according to their purpose. \n\n'
            +'  • Techniques: \n'
            +'Those that allow the user to navigate through a web page, web platform, platform or application and use the different options or services that exist therein and enable its functions and services. \n\n'
            +'  • Preferences or customization: \n'
            +'Those that allow the user to remember information so that they can access the service with certain characteristics that can differentiate their experience from that of other users. \n\n'
            +'  • Analysis or measurement: \n'
            +'They are those that allow the person responsible for them to monitor and analyze the behavior of the users of the websites to which they are linked, including the quantification of the impacts of the advertisements. The information collected through this type of cookies is used to measure the activity of the websites, application or platform, in order to introduce improvements based on the analysis of the usage data made by users of the service. \n\n'
            +'  • Behavioral advertising: \n'
            +'They store information on the behavior of users obtained through the continuous observation of their browsing habits, which allows to develop a specific profile to advertise based on it. \n\n'
            +'\n Limitations of cookies. \n\n'
            +' • The total number is limited to 300 \n'
            +' • The maximum size is 4Kb \n'
            +' • A maximum of 20 cookies per domain \n\n'
            +'\n A tracker as well as cookies are part of the navigation and function as follows each with its own type of tracker (Tracking) \n\n'
            +' • IP address tracking \n'
            +'The IP address is a device identifier on the Internet. Since the IP indicates the general physical location, websites use IP tracking to monitor where their visitors are coming from. They can also use IP addresses to identify patterns of behavior and determine whether repeat visits come from the same person. \n\n'
            +' • Web beacons: \n'
            +'Websites and emails use web beacons, a transparent single-pixel graphic image format, to record user behavior. \n\n'
            +' • Browser fingerprinting: \n\n'
            +'When you connect to a website, your browser transmits a large amount of data that the website uses to optimize your experience. This data includes the device model, screen resolution, operating system, preferred language, history, time zone, plugins used and other additional information. \n\n'
            +'\n Security vulnerabilities. \n\n'
            +'Theft of cookies, during normal operation, cookies are sent bidirectionally between servers (or group of servers on the same domain) and the computer of the user who is browsing. Since cookies can contain sensitive information (username, a token used for authentication, etc.), their values ​​should not be accessible from other computers. However, cookies sent over normal HTTP sessions are visible to everyone. users who can listen on the network using a packet sniffer. These cookies must not contain sensitive information. This problem can be solved by using https, which invokes transport layer security to encrypt the connection. \n\n'
            +'Fraudulent online stores, When we browse the Internet, third-party cookies record all the searches we carry out, for example for products and services. Using this stored data, fraud can occur in which users are redirected to fraudulent stores through misleading advertising that shows them sought-after items at very low prices. \n\n'
            +'Fake news, there is another variant in which users are incited to watch biased or sensationalist videos on a website of an owner or video uploaded on a platform. Their goal is to make money thanks to the advertising and traffic they receive. \n\n'
            +'Cookie theft or session hijacking, a modified cookie is introduced in the browser of the user who has visited a fraudulent website. Then, when accessing a website that requires entering credentials, the modified cookie pretends to be the legitimate cookie, obtaining the users authentication data. \n\n'
            +'\n Measures for the prevention of cookie theft:  \n\n'
            +' • Use private browsing \n'
            +' • Delete browser cookies periodically \n'
            +' • Log out of all websites when we stop using it, so that the cookie expires and can no longer be deleted. \n'
            +' • Use browser extensions that block and delete cookies: Vanilla Cookies Manager, Ghostery, Cookie AutoDelete \n'
            +'\n Bibliography. \n\n'
            +'Kaspersky. (2024). ¿Qué son las cookies?. Retrieved May 6, 2024 from https://www.kaspersky.es/resource-center/definitions/cookies\n\n'
            +'Elena Hernández. (2021). Cumplimiento normativo en el uso de las cookies en la web. Universitat Oberta de Cataluya (UOC). Retrieved May 6, 2024 from https://openaccess.uoc.edu/handle/10609/137987\n\n'
            +'Elena Diaz. (2021). Análisis, gestión y garantización del cumplimiento normativo en el uso de las cookies en la web.  Universitat Oberta de Cataluya (UOC). Retrieved May 6, 2024 from https://openaccess.uoc.edu/handle/10609/133667\n\n'
            +'\n\n'
          },

    { id: '3', title: 'Malware and types of malware', 
    content: 'Malware as its name suggests is malicious software that describes a malicious program that is harmful to systems, similar to viruses for humans. Malware can act in different ways being very hostile, intrusive, evading the system that tries to detect it, also damages or disables computer systems, networks, computers and mobile devices. \n\n'
            +'\n How do I know if I have a virus on my mobile device?\n\n'
            +' • It gets hot: \n'
            +'The internal components of your device immediately start working harder due to the malware or virus affecting it. \n\n'
            +' • Slower and slower: \n'
            +'It can cause websites to load slower, apps to crash, or the battery to not hold a charge. Overall performance remains slow no matter how many times the device is rebooted or how many large files are deleted. \n\n'
            +' • Pages open on their own and applications are installed on your cell phone.  \n'
            +'If your device is hosting a malicious application or virus, you may notice that you are getting pop-ups or pop-up windows (more than usual) on your phone. \n\n'
            +' • Fraudulent links from your accounts \n'
            +'A powerful tactic designed to spread malware to your contacts, and from them to your contacts, and so on. This can happen through email or, more commonly, through your social media accounts. \n\n'
            +' • You find unauthorized expenses \n'
            +'If you notice unauthorized charges on your credit card or bank statements, investigate further. It could be a malicious application making purchases on your behalf or a malicious program that has hijacked your personal data to make fraudulent purchases. \n\n'
            +'\n Types of malware. \n\n'
            +' • Virus: \n'
            +'Attaches to other programs, self-replicates, and spreads from one drive to another \n\n'
            +' • Malware: \n'
            +'They are programs designed by cybercriminals to cause damage or harm such as information theft. \n\n'
            +' • Spyware: \n'
            +'Any malicious software component that infects your computer and spies on your personal data. \n\n'
            +' • RootKits\n'
            +'These are tools used to hide processes and files that allow the intruder to maintain remote access. \n\n'
            +' • Backdoors: \n'
            +'Program that allows a backside through which it is possible to control the affected system without the users knowledge. \n\n'
            +' • Trojans: \n'
            +'A piece of malware disguised as genuine software that attempts to affect your computer and alter your files and data. \n\n'
            +' • Worms: \n'
            +'Subclass of viruses, their goal is to crash computers and computer networks. \n\n'
            +' • Keloggers:\n'
            +'They track and record every keystroke on a computer without the users permission or knowledge. \n\n'
            +'\n How to avoid malware. \n\n'
            +'• Stay tuned for updates. \n'
            +'• Use strong and unique passwords. \n'
            +'• Clear browsing history. \n'
            +'• Lock settings and limit app permissions. \n'
            +'• Know your apps and only install official apps from verified linked app stores. \n'
            +'• Dont click on just any link. Dont rush and watch your digital environment. Phishing scams that load malware and viruses on your cell phones often arrive in emails, text messages or through your trusted circles on social networks. \n'
            +'\n Bibliography. \n\n'
            +'Toni B. (2021). 5 Signs Your Device May be Infected with Malware or a Virus. McAfee. Retrieved May 6, 2024 from https://www.mcafee.com/blogs/mobile-security/5-signs-your-device-may-be-infected-with-malware-or-a-virus/\n\n'
            +'Kaspersky. (2024). What are cookies?. Retrieved May 6, 2024 from https://rcs.cic.ipn.mx/2016_115/RCS_115_2016.pdf\n\n'
            +'Malwarebytes. (2024). What is malware?. Malwarebytes. Retrieved May 6, 2024 from https://www.malwarebytes.com/malware\n\n'
            +'Noé C. (2016). Advances in Natural Language Processing and Computational Linguistics. Instituto Politécnico Nacion al, Centro de Investigación en Computación. Retrieved May 6, 2024 from https://rcs.cic.ipn.mx/2016_115/RCS_115_2016.pdf\n\n'
            +'\n\n'
            
          },

    { id: '4', title: 'OSINT', 
    content: 'We could say that we apply OSINT to get all the information available in any public source about a company, natural person or anything else we want to do an investigation on, and turning the whole accumulation of data into intelligence that serves us to be more effective in obtaining a result. Given some input data, together with the application of advanced collection and analysis techniques, OSINT continuously expands the knowledge about the target. In this way, the information found feeds back into the collection process. \n\n' 
            +'\n Methodology. \n\n'
            +'First, in the collection phase, publicly available data are retrieved from relevant open sources according to the objective or target. In particular, the Internet is the resource par excellence due to the volume of existing material and its easy accessibility. The collection process is particularly relevant because it is from this stage that the entire intelligence generation process is triggered. Then, in the analysis phase, the collected raw material is processed to generate valuable and understandable information. Data alone are not useful, so they must be interpreted to obtain the first facts derived from an in-depth analysis. Finally, in the knowledge extraction process, the previously refined information is taken as input for more sophisticated inference algorithms. \n\n'
            +' • Requirements: \n'
            +'What problem do we want to solve? What information do we need? \n\n'
            +' • Identification of information sources: \n'
            +'What sources can provide us with valuable and accurate information? \n\n'
            +' • Acquisition: \n'
            +'Information gathering stage \n\n'
            +' • Processing: \n'
            +'Format all the “raw” information obtained in the previous phase. \n\n'
            +' • Analysis: \n'
            +'Generate intelligence from all the data obtained, finding relationships between them that allow us to reach conclusions. \n\n'
            +' • Presentation: \n\n'
            +'Format the information in a way that it can be understood in an effective and simple manner. \n\n'
            +'\n Big Data and machine learning in OSINT. \n\n'
            +'Machine learning algorithms can automate and make research and decision-making processes smarter and more efficient. It makes it possible to detect complex correlations that are naturally unpredictable to humans. This point will be key in future OSINT activities, as it will make the difference between human-driven and AI-driven research. By incorporating these techniques, the collection and analysis process will definitely improve, thus resulting in accurate and close-to-target investigations. In addition, government counterintelligence agencies can leverage this paradigm to further improve the quality of information managed and, consequently, the battle against terrorist organizations. \n\n'
            +'\n Uses. \n\n'
            +'• Military, Identify and prevent potential military or national security threats. \n'
            +'• Policial: Buscar personas y hacerles un seguimiento.\n'
            +'• Financial: assess market trends, collect information for detective purposes, perform market analysis to launch marketing campaigns, obtain documentation for journalistic use. \n'
            +'• Technological: Knowing the online reputation of a company or a specific user, sociological, psychological or linguistic studies, cyber-attack prevention, pentesting recognition, auditing companies and organizations to assess their level of privacy and security. \n'
            +'\n OSINT Reasons. \n\n'
            +'In cybersecurity and cyber defense, ICT systems are continuously under attack by criminals with the aim of disrupting the availability of the services provided. Therefore, research becomes crucial to defend these systems from cyber attackers, namely by addressing the challenges that are still open in the field of cybersecurity. \n\n'
            +'Data mining techniques can help to perform analysis of daily attacks, correlate them and support decision-making processes for effective defense, but also for quick reaction. Similarly, OSINT can also be considered in this context as a source of information for traces and investigations. Digital forensics can incorporate OSINT to complement the digital evidence left behind by an incident. \n\n'
            +'Opinion and social sentiment analysis in social networks, it is possible to collect user interactions, messages, interests and preferences. extract non-explicit knowledge. The evidence accumulated in social networks is far-reaching and widely advantageous. Such collection and analysis is applied to marketing, political campaigns or disaster management. \n\n'
            +'Cybercrime and organized crime in them open data are continuously analyzed and compared by OSINT processes to detect criminal intentions at an early stage. scenario. Taking into account patterns of adversaries and relationships between serious crimes can provide law enforcement the opportunity to quickly detect. \n\n'
            +'\n Bibliography. \n\n'
            +'IL3. (2022). OSINT: qué es y técnicas más usadas. Instituto de Formación Continua, Universidad de Barcelona (IL3). Retrieved May 6, 2024 from www.il3.ub.edu/blog/osint-que-es-y-tecnicas-mas-usadas/\n\n'
            +'Javier P. (2019). The Not Yet Exploited Goldmine of OSINT: Opportunities, Open Challenges and Future Trends. IEEE Access. Retrieved May 6, 2024 from https://ieeexplore.ieee.org/abstract/document/8954668\n\n'
            +'Alberto F. (2021). What is OSINT, what is it and what is it for?. Derechodelared. Retrieved May 6, 2024 from https://derechodelared.com/osint/\n\n'
            +'\n\n'
        },

    { id: '5', title: 'Social engineering', 
    content: 'There is no doubt that in this digital era the most valuable asset is the information all organizations know that this information is shared with others in being an invasion of privacy for those users who surf the Internet. The great danger for all of us who use digital communication networks is the “social engineering” but what is it. \n\n'
            +'Described by Cristian B (2009). Social Engineering can be defined as an action or social behavior aimed at obtaining information from people close to a system. It is the art of obtaining from a third party those data of interest to the attacker by means of social skills. These practices are related to communication between human beings. \n\n'
            +'So with the approach the person seeking to manipulate knows that the user is the weakest link since no system is safe from human control. It is often thought in a very logical way in security that the only computer will be safe when it is unplugged, to which, Social Engineering often responds that there will always be an opportunity to convince a person to plug it in. This is why many crackers are dedicated to getting passwords the easy way and if it is by asking for the password, it saves them many hours of password cracking. \n\n'
            +'\n Why do you cooperate? \n\n'
            +'The human being is often tempted by give-and-take and commonly tends to give something in return after something else initially, by way of reciprocity, depending on the case and the scenario. Therefore the human beings reaction is controlled if he is convinced in the right way using urgency or pressure. \n\n'
            +'Cybercriminals deceive, but how they do it is that they usually impersonate an entity either by family members, technical support people, offer the victim prizes or unique and limited promotions in exchange for their data or for a product or discount, through co-workers or people they trust. The objective of this deception is to appropriate personal data, passwords or impersonate the identity of the person deceived.\n\n'
            +'\n Social engineering techniques. \n\n'
            +'There are techniques that take advantage of users and that we can observe to know that we are victims of social engineering. \n\n'
            +' • Vishing: \n'
            +'Through a phone call, the cybercriminal impersonates a family member, company personnel or technical support staff, stealing information.\n\n'
            +' • Phishing: \n'
            +'They send fake e-mails to obtain information from the victim. Requesting personal data, credit card, social security, work update, system passwords, they can create hostile situations so that the user does things without reasoning.\n\n'
            +' • Malicious devices: \n'
            +'A flash drive with malicious content is left in a public computer and this device obtains information about the person using it. \n\n'
            +' • Fake contests: \n'
            +'They inform the person who has won a prize in order to obtain personal information. \n\n'
            +' • Farming: \n'
            +'They make several communications with the victims until they obtain as much information as possible. \n\n'
            +' • Theft of e-mail accounts: \n'
            +'They steal real accounts to commit illicit acts among the victims contacts, send malicious software or to obtain personal information or impersonate mail support.\n\n'
            +'\n How to keep your guard up \n\n'
            +'Often these attacks are unpredictable, but there are ways to defend against them such as: never disclose sensitive information with strangers or in public places (such as social networks, advertisements, web pages, calls, etc.). If you suspect that someone is trying to perform a scam, demand identification and try to reverse the situation by trying to get as much information from the suspect, set up two-step authentication to be on the lookout for improper access to your accounts.\n\n'
            +'\n Bibliography. \n\n'
            +'Edgar S. (2011). Social Engineering: Corrupting the human mind. Universidad Nacional Autónoma de México (UNAM). Retrieved May 6, 2024 from https://www.ru.tic.unam.mx/handle/123456789/1750\n\n'
            +'Gobierno de Argentina. (2024). What is social engineering and how do I protect myself?. Retrieved May 6, 2024 from https://www.argentina.gob.ar/justicia/convosenlaweb/situaciones/que-es-la-ingenieria-social-y-como-protegerte\n\n'
            +'Cristian B. (2009). The infallible weapon: Social Engineering. Technical & Educational Manager de (ESET). Retrieved May 6, 2024 from https://www.informaticalegal.com.ar/wp-content/uploads/2011/09/Delitos-Informaticos.-ESET-El-arma-infalible-la-ingenieria-social.pdf\n\n'
            +'Juan P. (2021). Social engineering, a practical example. Revista Códigos.  Retrieved May 6, 2024 from https://revista.uisrael.edu.ec/index.php/ro/article/view/493\n\n'
            +'Claudia C. (2024). Phishing, vishing, smishing, what are they and how to protect yourself from these threats?. BBVA. Retrieved May 6, 2024 from https://www.bbva.com/es/innovacion/phishing-vishing-smishing-que-son-y-como-protegerse-de-estas-amenazas/\n\n'
            +'\n\n'
          }
  ]

  export default data;